

create TABLE stg.Account (
    tblId serial,
    OwnerId char (18) Null,
    Name varchar (255) Null,
    Account_Shortname__c varchar (255) Null,
    isDeleted Boolean  Null,
    MasterRecordId char (18) Null,
    Id char (18),
    Type varchar (40) Null,
    AccountSource varchar (255) Null,
    Account_Health__c varchar (255) Null,
    Account_Region__cc varchar (255) Null,
    Account_Status__c varchar (255) Null,
    AnnualRevenue NUMERIC (18,0) Null,
    IsPartner Boolean  Null,
    BillingStreet varchar (255) Null,
    BillingCity varchar (40) Null,
    BillingState varchar (80) Null,
    BillingStateCode varchar (20) Null,
    BillingPostalCode varchar (20) Null,
    BillingCountry varchar (80) Null,
    BillingCountryCode varchar (20) Null,
    Brand__c Boolean  Null,
    Brand_Affiliation__c char (18) Null,
    CreatedById char (18) Null,
    CRM__c varchar (62) Null,
    CSM__c varchar (62) Null,
    Days_Since_Last_Activity__c int  Null,
    NumberOfEmployees int  Null,
    HubSpot_ID__c int  Null,
    Industry varchar (255) Null,
    Intelity_Referral__c Boolean  Null,
    Intelity_Products__c varchar (1000) Null,
    LastModifiedById char (18) Null,
    Master_Brand__c varchar (30) Null,
    New_Build__c Boolean  Null,
    Number_of_Echos__c int  Null,
    Number_of_Lobby_Units__c int  Null,
    Number_of_Properties__c int  Null,
    Number_of_Rooms__c int  Null,
    Number_of_Tablets__c int  Null,
    Other__c varchar (25) Null,
    Other_System__c varchar (255) Null,
    Property_Type__c varchar (100) Null,
    Rating varchar (10) Null,
    Renovation__c Boolean  Null,
    SDR__c varchar (100) Null,
    Secondary_Account__c varchar (200) Null,
    MP_Mobile_Target__c Boolean  Null,
    MP_Mobile_Target_Notes__c varchar (255) Null,
    Territory__c varchar (100) Null,
    TV_Vendor__c varchar (26) Null,
    Website varchar (255) Null,
    PMS_System__c varchar (26) Null,
    POS_System__c varchar (26) Null,
    Ticket_Mgmt_System__c varchar (26) Null,
    Room_Controls_System__c varchar (26) Null,
    Spa_System__c varchar (26) Null,
    Door_Locks__c varchar (40) Null,
    ParentId char (18) Null,
    LastActivityDate Date  Null,
    lastModifiedDate timestamp with time zone  Null,
    SystemModstamp timestamp with time zone,
    CONSTRAINT PK_stg_Account PRIMARY KEY(id, SystemModstamp)
)